# Generated by Django 4.0.6 on 2022-07-29 16:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoApp',
            new_name='TodoModel',
        ),
    ]
